<#  
.SYNOPSIS 
	Import a CSV to generate a script which will perform individual VM HDD migrations
.DESCRIPTION
	Run this script to import a CSV generated by Export-VMDKs and modified to include
	a "TargetDatastore" column.  This script will generate a new script which will
	contain a series of single-line commands to migrate each individual VM HDD.
.NOTES
	Author: Allen Derusha
#>

################################################################################
# Define values for script execution
$strInputFile = "VMDK-Migration.csv"
$strOutputScript = "Migrate-VMDKs.ps1"

# Overwrite the existing script file if present
If (Test-Path $strOutputScript) { Remove-Item $strOutputScript }

ForEach ($myVMDK in Import-Csv $strInputFile) { 
	$strCLICommand = 'get-vm -name "' + $myVMDK.VMName + '" | Get-HardDisk -Name "' + $myVMDK.HDDName + '" | Move-HardDisk -Datastore (Get-Datastore -Name "' + $myVMDK.TargetDatastore + '") -Confirm:$false'
	Write-Host $strCLICommand
	Add-Content -Path $strOutputScript -Value $strCLICommand
} 